## numpy
- n 차원 배열 (ndarray)

In [4]:
# 넘파이 라이브러리 불러오기
import numpy as np

In [6]:
# 일반 파이썬 리스트
list = [1, 2, 10]
print(list * 3)

[1, 2, 10, 1, 2, 10, 1, 2, 10]


In [16]:
# 넘파이 배열
arr = np.array(list)
# 원소들간의 곱으로 이루어진 것을 확인할 수 있다
print(type(arr))
print(arr * 3)

<class 'numpy.ndarray'>
[ 3  6 30]


In [16]:
# 2차원 리스트로부터 2차원 배열을 만드는 예
data = [[1,2,3],[4,5,6],[7,8,9]]
print(data)
type(data)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


list

In [17]:

arr = np.array(data) # list를 ndarray로
print(arr)
type(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


numpy.ndarray

In [18]:
# 배열의 각 항목의 타입을 알아보려면 dtype 속성값을 보면 된다
arr.dtype

dtype('int32')

In [19]:
# 배열의 구조를 보려면 shape 속성을 보면 된다
arr.shape

(3, 3)

In [20]:
# 2차원 배열 원소 접근법
arr[1,2], arr[1][2]

(6, 6)

In [21]:
# 2차원 배열 원소 슬라이싱
arr[:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
# 초기값이 0인 배열을 만드는 법
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [24]:
# 레인지(범위)를 만드는 법
x = range(5)
print(type(x)) ; x

<class 'range'>


range(0, 5)

In [25]:
# 레인지 형태로 배열을 만드는 법
y = np.arange(5)
print(type(y)) ; y

<class 'numpy.ndarray'>


array([0, 1, 2, 3, 4])

In [26]:
x[2], y[2]

(2, 2)

In [27]:
# 데이터의 타입을 변경하려면 astype을 사용한다
z = y.astype(np.float32) ; z

array([0., 1., 2., 3., 4.], dtype=float32)

In [28]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
# 벡터화: 배열에 상수를 곱하거나 더할 수 있다
arr*2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [30]:
arr + 1000

array([[1001, 1002, 1003],
       [1004, 1005, 1006],
       [1007, 1008, 1009]])

In [60]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
# 배열을 곱하면 각 항목별로 곱셈을 한다
arr*arr

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [32]:
# 전체는 ':'로 표시할 수 있다
arr[:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
# 0~11 값을 얻고 이를 4x3 배열로 재구성한다
data = np.arange(12).reshape(4,3)
data

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [31]:
# 5 보다 큰 값을 모두 5로 교체하는 방법
data[data > 5] = 5
data

array([[0, 1, 2],
       [3, 4, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [32]:
data

array([[0, 1, 2],
       [3, 4, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [33]:
data.mean()

3.75

In [34]:
data[0]                # data[0]

array([0, 1, 2])

In [38]:
data[[0]]              # row number 0 인 row

array([[0, 1, 2]])

In [35]:
data

array([[0, 1, 2],
       [3, 4, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [36]:
data[[1,0]]         # 1,0 번째 row

array([[3, 4, 5],
       [0, 1, 2]])

In [37]:
# 행의 순서를 임의의 순으로 바꿀 수 있다
# 팬시 색인으로 배열을 바꾸면 본사본이 생기며 원래의 내용을 바뀌지 않는다
data[[3,2,1,0]]

array([[5, 5, 5],
       [5, 5, 5],
       [3, 4, 5],
       [0, 1, 2]])

In [38]:
data
# data 내용은 그대로 남아 있다

array([[0, 1, 2],
       [3, 4, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [39]:
data[[3,2,1,0]]

array([[5, 5, 5],
       [5, 5, 5],
       [3, 4, 5],
       [0, 1, 2]])

In [53]:
data[[3,2,1,0],[2]]

array([5, 5, 5, 2])

In [46]:
# 행과 열을 모두 바꾸려면 아래와 같이 한다
data[[3,2,1,0]][:,[2,1,0]]

array([[5, 5, 5],
       [5, 5, 5],
       [5, 4, 3],
       [2, 1, 0]])

In [63]:
data

array([[0, 1, 2],
       [3, 4, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [43]:
# 트랜스포즈는 행과 열의 위치를 바꾸는 것이다
data.T

array([[0, 3, 5, 5],
       [1, 4, 5, 5],
       [2, 5, 5, 5]])

In [44]:
# 배열의 곱셈은 np.dot()을 사용한다
np.dot(data,data.T)

array([[ 5, 14, 15, 15],
       [14, 50, 60, 60],
       [15, 60, 75, 75],
       [15, 60, 75, 75]])

In [64]:
data

array([[0, 1, 2],
       [3, 4, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [45]:
# 각 행에 대해서 평균을 구한다 axis=1이면 행을 지칭한다
data.mean(axis=1)

array([1., 4., 5., 5.])

In [46]:
# axis를 생략해도 된다
data.mean(1)

array([1., 4., 5., 5.])

In [66]:
data

array([[0, 1, 2],
       [3, 4, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [65]:
# 각 열에 대해서 평균을 구한다 axis=0이면 열을 지칭한다
data.mean(0)

array([3.25, 3.75, 4.25])

In [48]:
# 불리언 연산, True는 1로 False는 0으로 숫자로 치환하여 계산가능하다
1 + True

2

In [49]:
# 배열에서 값이 특정 수보다 큰 원소의 갯수를 반환한다.
x = np.array([1,2,3,4,5,6])
(x>4).sum()

2

In [67]:
data

array([[0, 1, 2],
       [3, 4, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [50]:
(data>1).sum()    # True 값을 더하기

10

In [68]:
x

array([1, 2, 3, 4, 5, 6])

In [51]:
(x>4)

array([False, False, False, False,  True,  True])

In [70]:
z = np.random.randint(0,100,10); z

array([98, 80, 14,  1, 85, 87, 12, 91,  7, 87])

In [53]:
z.sort() ; z

array([15, 26, 33, 41, 49, 56, 61, 63, 85, 92])

In [54]:
t = np.array([[8,4,11,5],[2,10,7,3],[9,12,1,6]])
t

array([[ 8,  4, 11,  5],
       [ 2, 10,  7,  3],
       [ 9, 12,  1,  6]])

In [55]:
# 열을 기준으로 각 행을 소팅
t.sort(0) ; t

array([[ 2,  4,  1,  3],
       [ 8, 10,  7,  5],
       [ 9, 12, 11,  6]])

In [56]:
# 행에서 소팅
t.sort(1) ; t

array([[ 1,  2,  3,  4],
       [ 5,  7,  8, 10],
       [ 6,  9, 11, 12]])

In [57]:
t

array([[ 1,  2,  3,  4],
       [ 5,  7,  8, 10],
       [ 6,  9, 11, 12]])

In [55]:
# 순서를 임의로 바꾸는 방법
z = np.arange(10) ; z

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
np.random.permutation(z)

array([5, 7, 1, 2, 4, 3, 9, 0, 6, 8])

In [57]:
z

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
np.random.shuffle(z)

In [60]:
z

array([8, 1, 5, 4, 3, 6, 2, 7, 0, 9])